SERVER_BASE_URL = '128.199.217.76:5000'
IMAGE_UPLOAD_DIR = SERVER_BASE_URL + '/static/uploads/'

# EDAMAM
EDAMAM_APP_ID = 'd7c674f0'
EDAMAM_APP_KEY = '42cf92ab91bd180ac1ede3aac7590732'
EDAMAM_FOOD_API = 'https://api.edamam.com/api/food-database/parser'
EDAMAM_NUTRIENTS_API = 'https://api.edamam.com/api/food-database/nutrients?app_id={app_id}&app_key={app_key}'

food_101 = {
    'apple_pie': 'Apple Pie',
    'baby_back_ribs': 'Baby Back Ribs',
    'baklava': 'Baklava',
    'beef_carpaccio': 'Beef Carpaccio',
    'beef_tartare': 'Beef Tartare',
    'beet_salad': 'Beet Salad',
    'beignets': 'Beignets',
    'bibimbap': 'Bibimbap',
    'bread_pudding': 'Bread Pudding',
    'breakfast_burrito': 'Breakfast Burrito',
    'bruschetta': 'Bruschetta',
    'caesar_salad': 'Caesar Salad',
    'cannoli': 'Cannoli',
    'caprese_salad': 'Caprese Salad',
    'carrot_cake': 'Carrot Cake',
    'ceviche': 'Ceviche',
    'cheesecake': 'Cheesecake',
    'cheese_plate': 'Cheese Plate',
    'chicken_curry': 'Chicken Curry',
    'chicken_quesadilla': 'Chicken Quesadilla',
    'chicken_wings': 'Chicken Wings',
    'chocolate_cake': 'Chocolate Cake',
    'chocolate_mousse': 'Chocolate Mousse',
    'churros': 'Churros',
    'clam_chowder': 'Clam Chowder',
    'club_sandwich': 'Club Sandwich',
    'crab_cakes': 'Crab Cakes',
    'creme_brulee': 'Creme Brulee',
    'croque_madame': 'Croque Madame',
    'cup_cakes': 'Cup Cakes',
    'deviled_eggs': 'Deviled Eggs',
    'donuts': 'Donuts',
    'dumplings': 'Dumplings',
    'edamame': 'Edamame',
    'eggs_benedict': 'Eggs Benedict',
    'escargots': 'Escargots',
    'falafel': 'Falafel',
    'filet_mignon': 'Filet Mignon',
    'fish_and_chips': 'Fish And Chips',
    'foie_gras': 'Foie Gras',
    'french_fries': 'French Fries',
    'french_onion_soup': 'French Onion Soup',
    'french_toast': 'French Toast',
    'fried_calamari': 'Fried Calamari',
    'fried_rice': 'Fried Rice',
    'frozen_yogurt': 'Frozen Yogurt',
    'garlic_bread': 'Garlic Bread',
    'gnocchi': 'Gnocchi',
    'greek_salad': 'Greek Salad',
    'grilled_cheese_sandwich': 'Grilled Cheese Sandwich',
    'grilled_salmon': 'Grilled Salmon',
    'guacamole': 'Guacamole',
    'gyoza': 'Gyoza',
    'hamburger': 'Hamburger',
    'hot_and_sour_soup': 'Hot And Sour Soup',
    'hot_dog': 'Hot Dog',
    'huevos_rancheros': 'Huevos Rancheros',
    'hummus': 'Hummus',
    'ice_cream': 'Ice Cream',
    'lasagna': 'Lasagna',
    'lobster_bisque': 'Lobster Bisque',
    'lobster_roll_sandwich': 'Lobster Roll Sandwich',
    'macaroni_and_cheese': 'Macaroni And Cheese',
    'macarons': 'Macarons',
    'miso_soup': 'Miso Soup',
    'mussels': 'Mussels',
    'nachos': 'Nachos',
    'omelette': 'Omelette',
    'onion_rings': 'Onion Rings',
    'oysters': 'Oysters',
    'pad_thai': 'Pad Thai',
    'paella': 'Paella',
    'pancakes': 'Pancakes',
    'panna_cotta': 'Panna Cotta',
    'peking_duck': 'Peking Duck',
    'pho': 'Pho',
    'pizza': 'Pizza',
    'pork_chop': 'Pork Chop',
    'poutine': 'Poutine',
    'prime_rib': 'Prime Rib',
    'pulled_pork_sandwich': 'Pulled Pork Sandwich',
    'ramen': 'Ramen',
    'ravioli': 'Ravioli',
    'red_velvet_cake': 'Red Velvet Cake',
    'risotto': 'Risotto',
    'samosa': 'Samosa',
    'sashimi': 'Sashimi',
    'scallops': 'Scallops',
    'seaweed_salad': 'Seaweed Salad',
    'shrimp_and_grits': 'Shrimp And Grits',
    'spaghetti_bolognese': 'Spaghetti Bolognese',
    'spaghetti_carbonara': 'Spaghetti Carbonara',
    'spring_rolls': 'Spring Rolls',
    'steak': 'Steak',
    'strawberry_shortcake': 'Strawberry Shortcake',
    'sushi': 'Sushi',
    'tacos': 'Tacos',
    'takoyaki': 'Takoyaki',
    'tiramisu': 'Tiramisu',
    'tuna_tartare': 'Tuna Tartare',
    'waffles': 'Waffles'
}
